TESTS=controller_board.test
DESIGN=controller_board
EAGLINT_HOME=../../Eagle-Lint/
RESOURCES_ROOT=../../QuadClass-Resources/
LBRS=$(wildcard ../../QuadClass-Quadcopter-Solution/lbr/*.lbr) $(wildcard lbr/*.lbr) $(wildcard $(RESOURCES_ROOT)/Eagle/lbr/*.lbr)
CHECKS=

include ../../QuadClass-Quadcopter-Solution/Make.rules
